version: '2'

services:
  elasticsearch:
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  logstash:
    build:
      context: .
      dockerfile: docker/logstash/Dockerfile
    command: -f /etc/logstash/conf.d/
    volumes:
      - "./docker/logstash/config:/etc/logstash/conf.d"
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
  kibana:
    build:
      context: .
      dockerfile: docker/kibana/Dockerfile
    volumes:
      - "./docker/kibana/config:/opt/kibana/config"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
