output:
  logstash:
    enabled: true
    hosts:
      - logstash:5044
    timeout: 15

filebeat:
  prospectors:
    -
      paths:
        - "/var/log/nginx/access.log"
      document_type: nginx-access
